name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize] #Without the 3 rows the events wont trigger on pull requests

permissions: read-all

jobs:
  
  simple_deployment_pipeline:
    runs-on: ubuntu-22.04
    environment: basic
    env:                           # 👈 move here
      MONGODB_URL_TESTS: ${{ secrets.MONGODB_URL_TESTS }}
      SECRET: ${{ secrets.SECRET }}
      PORT: ${{ secrets.PORT }}
    steps:

      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: rjstone/discord-webhook-notify@v2

        with:
          node-version: '20'
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Install dependencies fronted and backend
        run: cd ./part4-back && npm install && cd ../part5-front && npm install  
      
      - name: front style check
        run:  cd ./part5-front && npm run lint
      - name: front tests
        run: cd ./part5-front && npm run test
      - name: building front
        run: cd ./part4-back && npm run build:front
      - name: run backend test & integration tests
        run: cd ./part4-back && npm run test
        env:
          NODE_ENV: "test "
      - name: deploy fly
        run: cd ./part4-back && npm run deploy
        if: ${{ github.event_name == 'push' }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
      
      
    


  tag_release:  
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 
